// Generated by scripts/build.js — edit site.yaml instead.
// 2026-05-03T00:35:53.725Z

window.SITE_CONFIG = {
  "email": "jhamilton@olin.edu",
  "linkedin": "https://www.linkedin.com/in/james-keller-hamilton-2593b1328/",
  "status": "May 2026 — debugging FSAE electronics · Open to Fall 2026 Co-Op.",
  "skim": [
    {
      "eyebrow": "Education",
      "title": "Olin College, '28",
      "sub": "B.S. Electrical Engineering"
    },
    {
      "eyebrow": "Now",
      "title": "Project Manager",
      "sub": "Olin Electric Motorsports (FSAE)"
    },
    {
      "eyebrow": "Built",
      "titleNum": "5",
      "titleText": "EV builds",
      "sub": "E-bikes, motorcycles, an ATV"
    },
    {
      "eyebrow": "From",
      "title": "Washington, DC",
      "sub": "Currently in Needham, MA"
    }
  ],
  "about": [
    "I am an Electrical Engineering student at Olin College of Engineering with a focused passion for electric vehicles, battery technology, and power electronics. I combine my academic pursuits with extensive hands-on experience.",
    "My practical skills have been honed through numerous personal DIY projects, running my own business, and designing and manufacturing custom printed circuit boards for the Olin Electric Motorsports (FSAE) team, where I am now the project manager.",
    "I'm originally from Washington, DC, and plan to graduate Olin in 2028."
  ]
};
